import '../global.css';
import cn from 'classnames';
import { ConfigProvider, Layout } from 'antd';
import { theme } from '@antd-monorepo/shared/utils';
import { inter } from '@antd-monorepo/next/shared/utils';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="id"
      className={cn([inter.variable])}
    >
      <body>
        <ConfigProvider theme={theme}>
          <Layout>{children}</Layout>
        </ConfigProvider>
      </body>
    </html>
  );
}
